Add new :append_datetime param and fix dates to UTC.
pajapro/fastlane-plugin-changelog pull request #53
Opened 2020-12-17 22:28 UTC by donileo

This PR adds a new stamp_changelog action argument: `stamp_date_time`. Specifying true stamps the changelog in the format of standard iso8601 date time `"2020-12-17T22:25:13Z"`. By default it is false and when true it overrides stamp_date.
The date chosen, whether by specifying `stamp_date: true` or `stamp_date_time: true` are placed in the env variable `FL_UPDATE_DATE_VAL`, `FL_UPDATE_DATE_TIME_VAL` respectively.

It also fixes the error being given by fastlane that the stamp_date arg was not a string.

 I figure this PR may require some additional modifications depending on the needs of the project but I figured it could be built upon 😄.

2020-12-20 10:45 UTC, pajapro commented
Hi @donileo ,

thanks a lot for the idea how to improve the plugin and actual contribution ❤️. I understand your need from issue #52 

>  I'm looking to include the time along with the _date in the form_ of 2020-12-08T21:51Z

the approach (add additional `stamp_date_time` param in [`update_changelog.rb`](https://github.com/pajapro/fastlane-plugin-changelog/pull/53/files#diff-5dfcf79237a571887613da0721d2e9fdf1210ab9cbad501619c27988144de038) and [`stamp_changelog.rb`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L140-L145) ) you have chosen in this PR to satisfy your need is OK, but I see 2 potential problems long-term:
1. _testability & complexity_ : adding _an additional param_ increases the code complexity and what has to be tested
2. _confusion for users_ : it may be confusing at glance to figure out why this plugin has 2 params for date/time instead of just one 

## Suggestion for improvement:
Instead of adding a new param for date & time format, I suggest to enhance the existing [`stamp_date`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L134-L139) and **let the user specify (override) the (default) format of date/time**, here is how:
1. rename [`stamp_date`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L134-L139) param to something like.....e.g. `stamp_datetime_format`?
2. make [`stamp_date`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L134-L139)'s `default_value` [`%Y-%m-%d`](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/lib/fastlane/plugin/changelog/actions/update_changelog.rb#L52) - so that we stay backwards compatible.
3. make [`stamp_date`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L134-L139)'s [`is_string`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/stamp_changelog.rb#L138) `true`
4. Once we have the above interface in place, any user (such as yourself 😉) can pass in `stamp_datetime_format: %FT%T%:z`, which will result in `2020-12-08T21:51Z`
5. In the [`update_changelog.rb`](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/update_changelog.rb#L52-L58) you won't need this [if/else](https://github.com/pajapro/fastlane-plugin-changelog/blob/f2b890ba23b09807309179cd9a62be5118a1b71f/lib/fastlane/plugin/changelog/actions/update_changelog.rb#L52-L58) and instead leverage the [`strftime`](https://ruby-doc.org/core-2.6.3/Time.html#method-i-strftime) Ruby method to create date & time format specified via string 👍

2020-12-20 10:46 UTC, pajapro requested changes
See my comment about overall approach to satisfy the need to change format of the stamped date & time

2021-03-06 16:41 UTC, donileo commented
Wow I forgot about this 😄 lol. That's what happens when you get caught up with work, implement your own solution that works for your own cases and then forget about requested changes such as the above lol. Let's see if I can do this today 😄, no promises..

2021-03-06 17:45 UTC, donileo commented
Ok doing this now. Good suggestions. On the `make stamp_date's default_value %Y-%m-%d - so that we stay backwards compatible.` there is an issue with "staying compatible". Staying compatible means using `keep a changelog` bad time format of not specifying whether the date being stamped is in local time or UTC/Zulu time. If we assume they mean local their standard needs to specify the local timezone offset such as -0500 but they don't do that. Given all of that I'm making the default assumption that the time being stamped is UTC time and as such append `Z` to the end of the date formats to let the user know this.

2021-03-13 10:09 UTC, pajapro approved these changes
Nice, approve and going to release it 🎉 thank you for contribution once again @donileo

2021-03-13 10:11 UTC, pajapro approved these changes

2021-03-13 10:11 UTC, pajapro commented on spec/update_changelog_action_spec.rb
> +    it 'updates [Unreleased] section identifier appending a date via the default datetime format' do
Perfect

2021-03-13 11:04 UTC, merged

2021-03-13 16:01 UTC, donileo commented
@pajapro Thanks 👍, no problem. 

I think another change (not sure if its considered breaking) that needs to be mentioned in the release is that the actual stamped date is now in UTC format - not local since previously it was using `Time.now` which returned local time. I feel that is important enough to possibly even mention in other places like in the `stamp_datetime_format `for which I'll make a future PR. Please let me know your thoughts.

2021-03-13 16:06 UTC, pajapro commented
Good point, for now I at least updated release notes.